### PR TITLE
feat/gh actions pipelines

### PR DESCRIPTION
**Pull request by mmpetarpeshev**
We have to sync on workflow and gh events. 
Not sure are going to migrate it now to gh actions , but lets we have the PR open and discuss it.

### CODE REVIEW

**Comment by dincho** [comment]
In general I prefer to support CircleCI instead of GH actions, this repository is under foundation maintenance

**Comment by kenodressel** [comment]
If the foundation takes care of it I think the foundation should handle the deployment pipeline etc. So we can close this PR for now.

**Comment by mmpetarpeshev** [comment]
OKey, closing the PR.

**Comment by mmpetarpeshev** [comment]
> In general I prefer to support CircleCI instead of GH actions, this repository is under foundation maintenance

Okey, we had to sync earlier on that , closing for now.

**Pull request closed without merging**
